# Generated by Django 3.2.4 on 2021-06-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_watchlist_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(blank='True', choices=[('AL', 'None'), ('FS', 'Fashion'), ('TO', 'Toys'), ('EL', 'Electronics'), ('HO', 'Home'), ('ET', 'etc')], max_length=2),
        ),
    ]
